# Generated by Django 5.1.3 on 2024-12-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='previous_stripe_price',
            field=models.IntegerField(default=0),
        ),
    ]
