# Generated by Django 5.1.2 on 2024-10-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cursos',
            field=models.ManyToManyField(related_name='alumnos', to='app.curso'),
        ),
    ]
