# Generated by Django 5.1.2 on 2024-10-25 23:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_curso_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='imagen',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
