# Generated by Django 5.1.2 on 2024-10-27 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_nombre_tema_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tema',
            old_name='Curso',
            new_name='curso',
        ),
    ]
