# Generated by Django 5.1.2 on 2024-11-05 23:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_curso_tema_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
