# Generated by Django 5.1.2 on 2024-11-06 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_curso_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='tags',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
