# Generated by Django 5.1.2 on 2024-11-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_curso_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='calificacion',
            field=models.CharField(choices=[('cero', 'Cero'), ('uno', 'Uno'), ('dos', 'Dos'), ('tres', 'Tres'), ('cuatro', 'Cuatro'), ('cinco', 'Cinco')], default='cero'),
        ),
        migrations.AddField(
            model_name='curso',
            name='categoria',
            field=models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend')], default='backend'),
        ),
        migrations.AddField(
            model_name='curso',
            name='tipo',
            field=models.CharField(choices=[('snack', 'Snack'), ('curso', 'Curso')], default='curso'),
        ),
    ]
