# Generated by Django 5.1.3 on 2024-12-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_curso_stripe_price_curso_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='previous_stripe_price',
            field=models.IntegerField(default=999),
        ),
        migrations.AddField(
            model_name='curso',
            name='price_changed_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
